-- MySQL Script generated by MySQL Workbench
-- 03/13/17 12:27:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rdap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rdap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rdap` DEFAULT CHARACTER SET utf8 ;
USE `rdap` ;

-- -----------------------------------------------------
-- Table `rdap`.`entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity` (
  `ent_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ent_handle` VARCHAR(100) NULL,
  `ent_port43` VARCHAR(254) NULL,
  PRIMARY KEY (`ent_id`),
  UNIQUE INDEX `id_UNIQUE` (`ent_id` ASC),
  UNIQUE INDEX `handle_UNIQUE` (`ent_handle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`vcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`vcard` (
  `vca_id` BIGINT NOT NULL AUTO_INCREMENT,
  `vca_name` VARCHAR(100) NULL,
  `vca_company_name` VARCHAR(255) NULL,
  `vca_company_url` VARCHAR(255) NULL,
  `vca_email` VARCHAR(200) NULL,
  `vca_voice` VARCHAR(50) NULL,
  `vca_cellphone` VARCHAR(50) NULL,
  `vca_fax` VARCHAR(50) NULL,
  `vca_job_title` VARCHAR(200) NULL,
  PRIMARY KEY (`vca_id`),
  UNIQUE INDEX `vca_id_UNIQUE` (`vca_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`remark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`remark` (
  `rem_id` BIGINT NOT NULL AUTO_INCREMENT,
  `rem_title` VARCHAR(255) NULL,
  `rem_type` VARCHAR(255) NULL,
  `rem_lang` VARCHAR(255) NULL,
  PRIMARY KEY (`rem_id`),
  UNIQUE INDEX `rem_id_UNIQUE` (`rem_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`link` (
  `lin_id` BIGINT NOT NULL AUTO_INCREMENT,
  `lin_value` VARCHAR(45) NULL,
  `lin_rel` VARCHAR(45) NULL,
  `lin_href` VARCHAR(45) NULL,
  `lin_hreflang` VARCHAR(45) NULL,
  `lin_title` VARCHAR(45) NULL,
  `lin_media` VARCHAR(45) NULL,
  `lin_type` VARCHAR(45) NULL,
  PRIMARY KEY (`lin_id`),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`event_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`event_action` (
  `eac_id` SMALLINT NOT NULL,
  `eac_name` VARCHAR(100) NULL,
  PRIMARY KEY (`eac_id`),
  UNIQUE INDEX `eac_id_UNIQUE` (`eac_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`event` (
  `eve_id` BIGINT NOT NULL AUTO_INCREMENT,
  `eac_id` SMALLINT NOT NULL,
  `eve_actor` VARCHAR(45) NULL,
  `eve_date` DATETIME NULL,
  PRIMARY KEY (`eve_id`),
  UNIQUE INDEX `eve_id_UNIQUE` (`eve_id` ASC),
  INDEX `fk_event_event_action1_idx` (`eac_id` ASC),
  CONSTRAINT `fk_event_event_action1`
    FOREIGN KEY (`eac_id`)
    REFERENCES `rdap`.`event_action` (`eac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`roles` (
  `rol_id` TINYINT NOT NULL,
  `rol_name` VARCHAR(100) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`zone` (
  `zone_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `zone_name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`zone_id`),
  UNIQUE INDEX `ZONE_ID_UNIQUE` (`zone_id` ASC),
  UNIQUE INDEX `zone_name_UNIQUE` (`zone_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain` (
  `dom_id` BIGINT NOT NULL AUTO_INCREMENT,
  `dom_handle` VARCHAR(255) NULL,
  `dom_ldh_name` VARCHAR(64) NULL,
  `dom_unicode_name` VARCHAR(255) NULL,
  `dom_port43` VARCHAR(254) NULL,
  `zone_id` SMALLINT NOT NULL,
  PRIMARY KEY (`dom_id`, `zone_id`),
  INDEX `fk_DOMAIN_ZONE1_idx` (`zone_id` ASC),
  UNIQUE INDEX `dom_id_UNIQUE` (`dom_id` ASC),
  UNIQUE INDEX `dom_handle_UNIQUE` (`dom_handle` ASC),
  CONSTRAINT `fk_DOMAIN_ZONE1`
    FOREIGN KEY (`zone_id`)
    REFERENCES `rdap`.`zone` (`zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_entity_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_entity_roles` (
  `dom_id` BIGINT NOT NULL,
  `ent_id` BIGINT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`dom_id`, `ent_id`, `rol_id`),
  INDEX `fk_entity_roles_roles1_idx` (`rol_id` ASC),
  INDEX `fk_entity_roles_entity1_idx` (`ent_id` ASC),
  INDEX `fk_domain_entity_roles_domain1_idx` (`dom_id` ASC),
  UNIQUE INDEX `ux_domain_role_unique` (`dom_id` ASC, `rol_id` ASC),
  CONSTRAINT `fk_entity_roles_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rdap`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_roles_entity1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_entity_roles_domain1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`remark_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`remark_description` (
  `rde_order` MEDIUMINT NOT NULL,
  `rem_id` BIGINT NOT NULL,
  `rde_description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`rde_order`, `rem_id`),
  CONSTRAINT `fk_REMARK_DESCRIPTION_REMARK1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_remarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_remarks` (
  `ent_id` BIGINT NOT NULL,
  `rem_id` BIGINT NOT NULL,
  PRIMARY KEY (`ent_id`, `rem_id`),
  INDEX `fk_entity_remarks_remark1_idx` (`rem_id` ASC),
  UNIQUE INDEX `rem_id_UNIQUE` (`rem_id` ASC),
  CONSTRAINT `fk_ENTITY_REMARKS_ENTITY1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_remarks_remark1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`status` (
  `sta_id` SMALLINT NOT NULL,
  `sta_name` VARCHAR(100) NULL,
  PRIMARY KEY (`sta_id`),
  UNIQUE INDEX `sta_id_UNIQUE` (`sta_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_status` (
  `ent_id` BIGINT NOT NULL,
  `sta_id` SMALLINT NOT NULL,
  PRIMARY KEY (`ent_id`, `sta_id`),
  INDEX `fk_entity_status_status1_idx` (`sta_id` ASC),
  INDEX `fk_entity_status_entity1_idx` (`ent_id` ASC),
  CONSTRAINT `fk_entity_status_status1`
    FOREIGN KEY (`sta_id`)
    REFERENCES `rdap`.`status` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_status_entity1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_events` (
  `ent_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`ent_id`, `eve_id`),
  INDEX `fk_entity_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_ENTITY_EVENT_ENTITY1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_links` (
  `ent_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`ent_id`, `lin_id`),
  INDEX `fk_entity_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_ENTITY_LINK_ENTITY1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`country_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`country_code` (
  `ccd_id` SMALLINT UNSIGNED NOT NULL,
  `ccd_code` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ccd_id`),
  UNIQUE INDEX `ccd_id_UNIQUE` (`ccd_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`autonomous_system_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`autonomous_system_number` (
  `asn_id` BIGINT NOT NULL AUTO_INCREMENT,
  `asn_handle` VARCHAR(100) NOT NULL,
  `asn_start_autnum` BIGINT NOT NULL,
  `asn_end_autnum` BIGINT NOT NULL,
  `asn_name` VARCHAR(200) NULL DEFAULT NULL,
  `asn_type` VARCHAR(200) NULL DEFAULT NULL,
  `asn_port43` VARCHAR(254) NULL DEFAULT NULL,
  `ccd_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`asn_id`, `ccd_id`),
  UNIQUE INDEX `asn_handle_UNIQUE` (`asn_handle` ASC),
  UNIQUE INDEX `asn_id_UNIQUE` (`asn_id` ASC),
  INDEX `fk_autonomous_system_number_country_code1_idx` (`ccd_id` ASC),
  CONSTRAINT `fk_autonomous_system_number_country_code1`
    FOREIGN KEY (`ccd_id`)
    REFERENCES `rdap`.`country_code` (`ccd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`asn_entity_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`asn_entity_roles` (
  `asn_id` BIGINT NOT NULL,
  `ent_id` BIGINT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`asn_id`, `ent_id`, `rol_id`),
  INDEX `fk_ENTITY_AUTNUMS_autonomous_system_number1_idx` (`asn_id` ASC),
  INDEX `fk_asn_entity_roles_roles1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_ENTITY_AUTNUMS_ENTITY1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTITY_AUTNUMS_autonomous_system_number1`
    FOREIGN KEY (`asn_id`)
    REFERENCES `rdap`.`autonomous_system_number` (`asn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asn_entity_roles_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rdap`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver` (
  `nse_id` BIGINT NOT NULL AUTO_INCREMENT,
  `nse_handle` VARCHAR(100) NULL,
  `nse_ldh_name` VARCHAR(254) NULL DEFAULT NULL,
  `nse_unicode_name` VARCHAR(255) NULL,
  `nse_port43` VARCHAR(254) NULL DEFAULT NULL,
  PRIMARY KEY (`nse_id`),
  UNIQUE INDEX `nse_handle_UNIQUE` (`nse_handle` ASC),
  UNIQUE INDEX `nse_id_UNIQUE` (`nse_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_nameservers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_nameservers` (
  `dom_id` BIGINT NOT NULL,
  `nse_id` BIGINT NOT NULL,
  PRIMARY KEY (`dom_id`, `nse_id`),
  INDEX `fk_DOMAIN_NAMESERVERS_nameserver1_idx` (`nse_id` ASC),
  CONSTRAINT `fk_DOMAIN_NAMESERVERS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOMAIN_NAMESERVERS_nameserver1`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`secure_dns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`secure_dns` (
  `sdns_id` BIGINT NOT NULL AUTO_INCREMENT,
  `sdns_zone_signed` TINYINT(1) NOT NULL,
  `sdns_delegation_signed` TINYINT(1) NOT NULL,
  `sdns_max_sig_life` INT NULL,
  `dom_id` BIGINT NOT NULL,
  PRIMARY KEY (`sdns_id`),
  INDEX `fk_SECURE_DNS_DOMAIN1_idx` (`dom_id` ASC),
  UNIQUE INDEX `sdns_id_UNIQUE` (`sdns_id` ASC),
  CONSTRAINT `fk_SECURE_DNS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ds_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ds_data` (
  `dsd_id` BIGINT NOT NULL AUTO_INCREMENT,
  `sdns_id` BIGINT NOT NULL,
  `dsd_keytag` INT NOT NULL,
  `dsd_algorithm` INT NOT NULL,
  `dsd_digest` VARCHAR(255) NOT NULL,
  `dsd_digest_type` INT NOT NULL,
  PRIMARY KEY (`dsd_id`, `sdns_id`),
  INDEX `fk_ds_data_secure_dns1_idx` (`sdns_id` ASC),
  UNIQUE INDEX `dsd_id_UNIQUE` (`dsd_id` ASC),
  CONSTRAINT `fk_ds_data_secure_dns1`
    FOREIGN KEY (`sdns_id`)
    REFERENCES `rdap`.`secure_dns` (`sdns_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_status` (
  `dom_id` BIGINT NOT NULL,
  `sta_id` SMALLINT NOT NULL,
  PRIMARY KEY (`dom_id`, `sta_id`),
  INDEX `fk_domain_status_status1_idx` (`sta_id` ASC),
  CONSTRAINT `fk_DOMAIN_STATUS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_status_status1`
    FOREIGN KEY (`sta_id`)
    REFERENCES `rdap`.`status` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_remarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_remarks` (
  `dom_id` BIGINT NOT NULL,
  `rem_id` BIGINT NOT NULL,
  PRIMARY KEY (`dom_id`, `rem_id`),
  INDEX `fk_domain_remarks_remark1_idx` (`rem_id` ASC),
  UNIQUE INDEX `rem_id_UNIQUE` (`rem_id` ASC),
  CONSTRAINT `fk_DOMAIN_REMARKS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_remarks_remark1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_links` (
  `dom_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`dom_id`, `lin_id`),
  INDEX `fk_domain_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_DOMAIN_LINKS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_events` (
  `dom_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`dom_id`, `eve_id`),
  INDEX `fk_domain_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_DOMAIN_EVENTS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_version` (
  `ive_id` TINYINT UNSIGNED NOT NULL,
  `ive_name` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ive_id`),
  UNIQUE INDEX `ipv_name_UNIQUE` (`ive_name` ASC),
  UNIQUE INDEX `ipv_id_UNIQUE` (`ive_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network` (
  `ine_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ine_handle` VARCHAR(255) NOT NULL,
  `ine_start_address_up` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ine_start_address_down` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ine_end_address_up` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ine_end_address_down` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ine_name` VARCHAR(255) NULL DEFAULT NULL,
  `ine_type` VARCHAR(255) NULL DEFAULT NULL,
  `ine_port43` VARCHAR(254) NULL DEFAULT NULL,
  `ccd_id` SMALLINT UNSIGNED NOT NULL,
  `ip_version_id` TINYINT UNSIGNED NOT NULL,
  `ine_parent_handle` VARCHAR(255) NULL,
  `ine_cidr` SMALLINT NULL,
  PRIMARY KEY (`ine_id`, `ine_handle`),
  UNIQUE INDEX `ine_handle_UNIQUE` (`ine_handle` ASC),
  UNIQUE INDEX `ine_id_UNIQUE` (`ine_id` ASC),
  INDEX `fk_ip_network_country_code1_idx` (`ccd_id` ASC),
  INDEX `fk_ip_network_ip_version1_idx` (`ip_version_id` ASC),
  INDEX `ipv4_start_idx` USING BTREE (`ine_start_address_down` ASC),
  INDEX `ipv4_end_idx` USING BTREE (`ine_end_address_down` ASC),
  INDEX `ipv6_start_idx` USING BTREE (`ine_start_address_up` ASC, `ine_start_address_down` ASC),
  INDEX `ipv6_end_idx` USING BTREE (`ine_end_address_up` ASC, `ine_end_address_down` ASC),
  CONSTRAINT `fk_ip_network_country_code1`
    FOREIGN KEY (`ccd_id`)
    REFERENCES `rdap`.`country_code` (`ccd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_ip_version1`
    FOREIGN KEY (`ip_version_id`)
    REFERENCES `rdap`.`ip_version` (`ive_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_networks` (
  `dom_id` BIGINT NOT NULL,
  `ine_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`dom_id`, `ine_id`),
  INDEX `fk_DOMAIN_NETWORKS_ip_network1_idx` (`ine_id` ASC),
  CONSTRAINT `fk_DOMAIN_NETWORKS_DOMAIN1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOMAIN_NETWORKS_ip_network1`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ds_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ds_events` (
  `dsd_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`dsd_id`, `eve_id`),
  INDEX `fk_ds_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `event_eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_DS_EVENTS_DS_DATA1`
    FOREIGN KEY (`dsd_id`)
    REFERENCES `rdap`.`ds_data` (`dsd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ds_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ds_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ds_links` (
  `dsd_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`dsd_id`, `lin_id`),
  INDEX `fk_ds_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_DS_LINKS_DS_DATA1`
    FOREIGN KEY (`dsd_id`)
    REFERENCES `rdap`.`ds_data` (`dsd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ds_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver_status` (
  `nse_id` BIGINT NOT NULL,
  `sta_id` SMALLINT NOT NULL,
  PRIMARY KEY (`nse_id`, `sta_id`),
  INDEX `fk_nameserver_status_status1_idx` (`sta_id` ASC),
  CONSTRAINT `fk_nameserver_status_nameserver`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameserver_status_status1`
    FOREIGN KEY (`sta_id`)
    REFERENCES `rdap`.`status` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_address` (
  `iad_id` INT NOT NULL AUTO_INCREMENT,
  `nse_id` BIGINT NOT NULL,
  `iad_type` TINYINT NOT NULL,
  `iad_value` VARBINARY(16) NOT NULL,
  PRIMARY KEY (`iad_id`, `nse_id`),
  UNIQUE INDEX `iad_id_UNIQUE` (`iad_id` ASC),
  CONSTRAINT `fk_nameserver_ip_addresses_nameserver1`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver_remarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver_remarks` (
  `nse_id` BIGINT NOT NULL,
  `rem_id` BIGINT NOT NULL,
  PRIMARY KEY (`nse_id`, `rem_id`),
  INDEX `fk_nameserver_remarks_remark1_idx` (`rem_id` ASC),
  UNIQUE INDEX `rem_id_UNIQUE` (`rem_id` ASC),
  CONSTRAINT `fk_nameserver_entities_nameserver10`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameserver_remarks_remark1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver_links` (
  `nse_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`nse_id`, `lin_id`),
  INDEX `fk_nameserver_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_nameserver_entities_nameserver100`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameserver_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`asn_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`asn_status` (
  `asn_id` BIGINT NOT NULL,
  `sta_id` SMALLINT NOT NULL,
  PRIMARY KEY (`asn_id`, `sta_id`),
  INDEX `fk_asn_status_status1_idx` (`sta_id` ASC),
  CONSTRAINT `fk_asn_status_autonomous_system_number1`
    FOREIGN KEY (`asn_id`)
    REFERENCES `rdap`.`autonomous_system_number` (`asn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asn_status_status1`
    FOREIGN KEY (`sta_id`)
    REFERENCES `rdap`.`status` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`asn_remarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`asn_remarks` (
  `asn_id` BIGINT NOT NULL,
  `rem_id` BIGINT NOT NULL,
  PRIMARY KEY (`asn_id`, `rem_id`),
  INDEX `fk_asn_remarks_remark1_idx` (`rem_id` ASC),
  UNIQUE INDEX `rem_id_UNIQUE` (`rem_id` ASC),
  CONSTRAINT `fk_asn_status_autonomous_system_number10`
    FOREIGN KEY (`asn_id`)
    REFERENCES `rdap`.`autonomous_system_number` (`asn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asn_remarks_remark1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`asn_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`asn_links` (
  `asn_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`asn_id`, `lin_id`),
  INDEX `fk_asn_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_asn_status_autonomous_system_number12`
    FOREIGN KEY (`asn_id`)
    REFERENCES `rdap`.`autonomous_system_number` (`asn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asn_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`asn_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`asn_events` (
  `asn_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`asn_id`, `eve_id`),
  INDEX `fk_asn_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_asn_status_autonomous_system_number120`
    FOREIGN KEY (`asn_id`)
    REFERENCES `rdap`.`autonomous_system_number` (`asn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asn_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_status` (
  `ine_id` BIGINT UNSIGNED NOT NULL,
  `sta_id` SMALLINT NOT NULL,
  PRIMARY KEY (`ine_id`, `sta_id`),
  INDEX `fk_ip_network_status_status1_idx` (`sta_id` ASC),
  CONSTRAINT `fk_ip_network_status_ip_network1`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_status_status1`
    FOREIGN KEY (`sta_id`)
    REFERENCES `rdap`.`status` (`sta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_remarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_remarks` (
  `ine_id` BIGINT UNSIGNED NOT NULL,
  `rem_id` BIGINT NOT NULL,
  PRIMARY KEY (`ine_id`, `rem_id`),
  INDEX `fk_ip_network_remarks_remark1_idx` (`rem_id` ASC),
  UNIQUE INDEX `remark_rem_id_UNIQUE` (`rem_id` ASC),
  CONSTRAINT `fk_ip_network_status_ip_network100`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_remarks_remark1`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_links` (
  `ine_id` BIGINT UNSIGNED NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`ine_id`, `lin_id`),
  INDEX `fk_ip_network_links_link1_idx` (`lin_id` ASC),
  UNIQUE INDEX `lin_id_UNIQUE` (`lin_id` ASC),
  CONSTRAINT `fk_ip_network_status_ip_network101`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_events` (
  `ine_id` BIGINT UNSIGNED NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`ine_id`, `eve_id`),
  INDEX `fk_ip_network_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `event_eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_ip_network_status_ip_network102`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`variant` (
  `var_id` BIGINT NOT NULL AUTO_INCREMENT,
  `var_idn_table` VARCHAR(100) NULL,
  `dom_id` BIGINT NOT NULL,
  PRIMARY KEY (`var_id`, `dom_id`),
  INDEX `fk_variant_domain1_idx` (`dom_id` ASC),
  UNIQUE INDEX `var_id_UNIQUE` (`var_id` ASC),
  CONSTRAINT `fk_variant_domain1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`relation` (
  `rel_id` TINYINT NOT NULL,
  `rel_type` VARCHAR(255) NULL,
  PRIMARY KEY (`rel_id`),
  UNIQUE INDEX `rel_id_UNIQUE` (`rel_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`variant_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`variant_name` (
  `vna_ldh_name` VARCHAR(63) NULL,
  `var_id` BIGINT NOT NULL,
  UNIQUE INDEX `vna_ldh_name_UNIQUE` (`vna_ldh_name` ASC),
  CONSTRAINT `fk_VARIANT_NAME_VARIANT1`
    FOREIGN KEY (`var_id`)
    REFERENCES `rdap`.`variant` (`var_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`vcard_postal_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`vcard_postal_info` (
  `vpi_id` BIGINT NOT NULL AUTO_INCREMENT,
  `vca_id` BIGINT NOT NULL,
  `vpi_type` VARCHAR(45) NULL,
  `vpi_country` VARCHAR(100) NULL,
  `vpi_city` VARCHAR(100) NULL,
  `vpi_street1` VARCHAR(100) NULL,
  `vpi_street2` VARCHAR(100) NULL,
  `vpi_street3` VARCHAR(100) NULL,
  `vpi_state` VARCHAR(100) NULL,
  `vpi_postal_code` VARCHAR(100) NULL,
  PRIMARY KEY (`vpi_id`, `vca_id`),
  UNIQUE INDEX `vca_id_UNIQUE` (`vpi_id` ASC),
  INDEX `fk_vcard_postal_info_vcard1_idx` (`vca_id` ASC),
  CONSTRAINT `fk_vcard_postal_info_vcard1`
    FOREIGN KEY (`vca_id`)
    REFERENCES `rdap`.`vcard` (`vca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver_events` (
  `nse_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`nse_id`, `eve_id`),
  INDEX `fk_nameserver_events_event1_idx` (`eve_id` ASC),
  UNIQUE INDEX `eve_id_UNIQUE` (`eve_id` ASC),
  CONSTRAINT `fk_nameserver_events_nameserver1`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameserver_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`public_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`public_id` (
  `pid_id` BIGINT NOT NULL AUTO_INCREMENT,
  `pid_type` VARCHAR(255) NULL,
  `pid_identifier` VARCHAR(255) NULL,
  PRIMARY KEY (`pid_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`domain_public_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`domain_public_ids` (
  `dom_id` BIGINT NOT NULL,
  `pid_id` BIGINT NOT NULL,
  PRIMARY KEY (`dom_id`, `pid_id`),
  INDEX `fk_domain_public_ids_public_id1_idx` (`pid_id` ASC),
  UNIQUE INDEX `public_id_pid_id_UNIQUE` (`pid_id` ASC),
  CONSTRAINT `fk_domain_public_ids_domain1`
    FOREIGN KEY (`dom_id`)
    REFERENCES `rdap`.`domain` (`dom_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_public_ids_public_id1`
    FOREIGN KEY (`pid_id`)
    REFERENCES `rdap`.`public_id` (`pid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_public_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_public_ids` (
  `ent_id` BIGINT NOT NULL,
  `pid_id` BIGINT NOT NULL,
  PRIMARY KEY (`ent_id`, `pid_id`),
  INDEX `fk_domain_public_ids_public_id1_idx` (`pid_id` ASC),
  UNIQUE INDEX `public_id_pid_id_UNIQUE` (`pid_id` ASC),
  INDEX `fk_domain_public_ids_copy2_entity1_idx` (`ent_id` ASC),
  CONSTRAINT `fk_domain_public_ids_public_id11`
    FOREIGN KEY (`pid_id`)
    REFERENCES `rdap`.`public_id` (`pid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domain_public_ids_copy2_entity1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`event_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`event_links` (
  `eve_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`eve_id`, `lin_id`),
  INDEX `fk_event_has_link_link1_idx` (`lin_id` ASC),
  INDEX `fk_event_has_link_event1_idx` (`eve_id` ASC),
  CONSTRAINT `fk_event_has_link_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_link_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`remark_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`remark_links` (
  `rem_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`rem_id`, `lin_id`),
  INDEX `fk_remark_has_link_link2_idx` (`lin_id` ASC),
  INDEX `fk_remark_has_link_remark2_idx` (`rem_id` ASC),
  CONSTRAINT `fk_remark_has_link_remark2`
    FOREIGN KEY (`rem_id`)
    REFERENCES `rdap`.`remark` (`rem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remark_has_link_link2`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`variant_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`variant_relation` (
  `rel_id` TINYINT NOT NULL,
  `var_id` BIGINT NOT NULL,
  PRIMARY KEY (`rel_id`, `var_id`),
  INDEX `fk_relation_has_variant_variant1_idx` (`var_id` ASC),
  INDEX `fk_relation_has_variant_relation1_idx` (`rel_id` ASC),
  CONSTRAINT `fk_relation_has_variant_relation1`
    FOREIGN KEY (`rel_id`)
    REFERENCES `rdap`.`relation` (`rel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_has_variant_variant1`
    FOREIGN KEY (`var_id`)
    REFERENCES `rdap`.`variant` (`var_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_contact` (
  `ent_id` BIGINT NOT NULL,
  `vca_id` BIGINT NOT NULL,
  PRIMARY KEY (`ent_id`, `vca_id`),
  INDEX `fk_entity_contact_vcard1_idx` (`vca_id` ASC),
  CONSTRAINT `fk_entity_contact_entity1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_contact_vcard1`
    FOREIGN KEY (`vca_id`)
    REFERENCES `rdap`.`vcard` (`vca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`nameserver_entity_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`nameserver_entity_roles` (
  `nse_id` BIGINT NOT NULL,
  `ent_id` BIGINT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`nse_id`, `ent_id`, `rol_id`),
  INDEX `fk_entity_roles_roles1_idx` (`rol_id` ASC),
  INDEX `fk_entity_roles_entity1_idx` (`ent_id` ASC),
  INDEX `fk_nameserver_entity_roles_nameserver1_idx` (`nse_id` ASC),
  CONSTRAINT `fk_entity_roles_roles10`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rdap`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_roles_entity10`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameserver_entity_roles_nameserver1`
    FOREIGN KEY (`nse_id`)
    REFERENCES `rdap`.`nameserver` (`nse_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`entity_entity_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`entity_entity_roles` (
  `main_ent_id` BIGINT NOT NULL,
  `ent_id` BIGINT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`main_ent_id`, `ent_id`, `rol_id`),
  INDEX `fk_entity_roles_roles1_idx` (`rol_id` ASC),
  INDEX `fk_entity_roles_entity1_idx` (`ent_id` ASC),
  INDEX `fk_entity_entity_roles_entity1_idx` (`main_ent_id` ASC),
  CONSTRAINT `fk_entity_roles_roles100`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rdap`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_roles_entity100`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entity_entity_roles_entity1`
    FOREIGN KEY (`main_ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`rdap_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`rdap_user` (
  `rus_name` VARCHAR(100) NOT NULL,
  `rus_pass` VARCHAR(200) NOT NULL,
  `rus_max_search_results` INT NULL,
  PRIMARY KEY (`rus_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`rdap_access_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`rdap_access_role` (
  `rar_name` VARCHAR(45) NOT NULL,
  `rar_description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`rar_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`rdap_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`rdap_user_role` (
  `rus_name` VARCHAR(100) NOT NULL,
  `rar_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rus_name`, `rar_name`),
  CONSTRAINT `rdap_user_ir_fk`
    FOREIGN KEY (`rus_name`)
    REFERENCES `rdap`.`rdap_user` (`rus_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rdap_access_role_ir_fk`
    FOREIGN KEY (`rar_name`)
    REFERENCES `rdap`.`rdap_access_role` (`rar_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_entity_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_entity_roles` (
  `ine_id` BIGINT UNSIGNED NOT NULL,
  `ent_id` BIGINT NOT NULL,
  `rol_id` TINYINT NOT NULL,
  PRIMARY KEY (`ine_id`, `ent_id`, `rol_id`),
  INDEX `fk_ipn_entity_roles_ip_network1_idx` (`ine_id` ASC),
  INDEX `fk_ipn_entity_roles_roles1_idx` (`rol_id` ASC),
  CONSTRAINT `fk_ipn_entity_roles_entity1`
    FOREIGN KEY (`ent_id`)
    REFERENCES `rdap`.`entity` (`ent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ipn_entity_roles_ip_network1`
    FOREIGN KEY (`ine_id`)
    REFERENCES `rdap`.`ip_network` (`ine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ipn_entity_roles_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rdap`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`ip_network_parent_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`ip_network_parent_relation` (
  `ine_parent_handle` VARCHAR(255) NOT NULL,
  `ine_son_handle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ine_parent_handle`, `ine_son_handle`),
  INDEX `fk_ip_network_parent_relation_ip_network2_idx` (`ine_son_handle` ASC),
  UNIQUE INDEX `ine_son_handle_UNIQUE` (`ine_son_handle` ASC),
  CONSTRAINT `fk_ip_network_parent_relation_ip_network1`
    FOREIGN KEY (`ine_parent_handle`)
    REFERENCES `rdap`.`ip_network` (`ine_handle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_network_parent_relation_ip_network2`
    FOREIGN KEY (`ine_son_handle`)
    REFERENCES `rdap`.`ip_network` (`ine_handle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`configuration` (
  `con_name` VARCHAR(255) NOT NULL,
  `con_value` VARCHAR(255) NULL,
  `con_previous_value` VARCHAR(255) NULL,
  `con_description` VARCHAR(255) NULL,
  `con_create_time` DATETIME NULL,
  `con_last_update` DATETIME NULL,
  PRIMARY KEY (`con_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`key_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`key_data` (
  `kd_id` BIGINT NOT NULL AUTO_INCREMENT,
  `sdns_id` BIGINT NOT NULL,
  `kd_flags` INT UNSIGNED NULL,
  `kd_protocol` INT UNSIGNED NULL,
  `kd_public_key` VARCHAR(255) NULL,
  `kd_algorithm` INT UNSIGNED NULL,
  PRIMARY KEY (`kd_id`, `sdns_id`),
  INDEX `fk_key_data_secure_dns1_idx` (`sdns_id` ASC),
  CONSTRAINT `fk_key_data_secure_dns1`
    FOREIGN KEY (`sdns_id`)
    REFERENCES `rdap`.`secure_dns` (`sdns_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`key_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`key_links` (
  `kd_id` BIGINT NOT NULL,
  `lin_id` BIGINT NOT NULL,
  PRIMARY KEY (`kd_id`, `lin_id`),
  INDEX `fk_key_links_link1_idx` (`lin_id` ASC),
  CONSTRAINT `fk_key_links_key_data1`
    FOREIGN KEY (`kd_id`)
    REFERENCES `rdap`.`key_data` (`kd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_key_links_link1`
    FOREIGN KEY (`lin_id`)
    REFERENCES `rdap`.`link` (`lin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rdap`.`key_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdap`.`key_events` (
  `kd_id` BIGINT NOT NULL,
  `eve_id` BIGINT NOT NULL,
  PRIMARY KEY (`kd_id`, `eve_id`),
  INDEX `fk_key_events_event1_idx` (`eve_id` ASC),
  CONSTRAINT `fk_key_events_key_data1`
    FOREIGN KEY (`kd_id`)
    REFERENCES `rdap`.`key_data` (`kd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_key_events_event1`
    FOREIGN KEY (`eve_id`)
    REFERENCES `rdap`.`event` (`eve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert catalogs
-- -----------------------------------------------------

INSERT INTO rdap.status VALUES(1,'validated');
INSERT INTO rdap.status VALUES(2,'renew prohibited');
INSERT INTO rdap.status VALUES(3,'update prohibited');
INSERT INTO rdap.status VALUES(4,'transfer prohibited');
INSERT INTO rdap.status VALUES(5,'delete prohibited');
INSERT INTO rdap.status VALUES(6,'proxy');
INSERT INTO rdap.status VALUES(7,'private');
INSERT INTO rdap.status VALUES(8,'removed');
INSERT INTO rdap.status VALUES(9,'obscured');
INSERT INTO rdap.status VALUES(10,'associated');
INSERT INTO rdap.status VALUES(11,'active');
INSERT INTO rdap.status VALUES(12,'inactive');
INSERT INTO rdap.status VALUES(13,'locked');
INSERT INTO rdap.status VALUES(14,'pending create');
INSERT INTO rdap.status VALUES(15,'pending renew');
INSERT INTO rdap.status VALUES(16,'pending transfer');
INSERT INTO rdap.status VALUES(17,'pending update');
INSERT INTO rdap.status VALUES(18,'pending delete');

INSERT INTO rdap.event_action VALUES(1,'registration');
INSERT INTO rdap.event_action VALUES(2,'reregistration');
INSERT INTO rdap.event_action VALUES(3,'last changed');
INSERT INTO rdap.event_action VALUES(4,'expiration');
INSERT INTO rdap.event_action VALUES(5,'deletion');
INSERT INTO rdap.event_action VALUES(6,'reinstantiation');
INSERT INTO rdap.event_action VALUES(7,'transfer');
INSERT INTO rdap.event_action VALUES(8,'locked');
INSERT INTO rdap.event_action VALUES(9,'unlocked');
INSERT INTO rdap.event_action VALUES(10,'last update of RDAP database');
INSERT INTO rdap.event_action VALUES(11,'registrar expiration');
INSERT INTO rdap.event_action VALUES(12,'enum validation expiration');

INSERT INTO rdap.relation VALUES(1, 'registered');
INSERT INTO rdap.relation VALUES(2, 'unregistered');
INSERT INTO rdap.relation VALUES(3, 'registration restricted');
INSERT INTO rdap.relation VALUES(4, 'open registration');
INSERT INTO rdap.relation VALUES(5, 'conjoined');

INSERT INTO rdap.roles VALUES (1,'registrant');
INSERT INTO rdap.roles VALUES (2,'technical');
INSERT INTO rdap.roles VALUES (3,'administrative');
INSERT INTO rdap.roles VALUES (4,'abuse');
INSERT INTO rdap.roles VALUES (5,'billing');
INSERT INTO rdap.roles VALUES (6,'registrar');
INSERT INTO rdap.roles VALUES (7,'reseller');
INSERT INTO rdap.roles VALUES (8,'sponsor');
INSERT INTO rdap.roles VALUES (9,'proxy');
INSERT INTO rdap.roles VALUES (10,'notifications');
INSERT INTO rdap.roles VALUES (11,'noc');

INSERT INTO rdap.country_code VALUES (4,'AF');
INSERT INTO rdap.country_code VALUES (248,'AX');
INSERT INTO rdap.country_code VALUES (8,'AL');
INSERT INTO rdap.country_code VALUES (12,'DZ');
INSERT INTO rdap.country_code VALUES (16,'AS');
INSERT INTO rdap.country_code VALUES (20,'AD');
INSERT INTO rdap.country_code VALUES (24,'AO');
INSERT INTO rdap.country_code VALUES (660,'AI');
INSERT INTO rdap.country_code VALUES (10,'AQ');
INSERT INTO rdap.country_code VALUES (28,'AG');
INSERT INTO rdap.country_code VALUES (32,'AR');
INSERT INTO rdap.country_code VALUES (51,'AM');
INSERT INTO rdap.country_code VALUES (533,'AW');
INSERT INTO rdap.country_code VALUES (36,'AU');
INSERT INTO rdap.country_code VALUES (40,'AT');
INSERT INTO rdap.country_code VALUES (31,'AZ');
INSERT INTO rdap.country_code VALUES (44,'BS');
INSERT INTO rdap.country_code VALUES (48,'BH');
INSERT INTO rdap.country_code VALUES (50,'BD');
INSERT INTO rdap.country_code VALUES (52,'BB');
INSERT INTO rdap.country_code VALUES (112,'BY');
INSERT INTO rdap.country_code VALUES (56,'BE');
INSERT INTO rdap.country_code VALUES (84,'BZ');
INSERT INTO rdap.country_code VALUES (204,'BJ');
INSERT INTO rdap.country_code VALUES (60,'BM');
INSERT INTO rdap.country_code VALUES (64,'BT');
INSERT INTO rdap.country_code VALUES (68,'BO');
INSERT INTO rdap.country_code VALUES (70,'BA');
INSERT INTO rdap.country_code VALUES (72,'BW');
INSERT INTO rdap.country_code VALUES (74,'BV');
INSERT INTO rdap.country_code VALUES (76,'BR');
INSERT INTO rdap.country_code VALUES (92,'VG');
INSERT INTO rdap.country_code VALUES (86,'IO');
INSERT INTO rdap.country_code VALUES (96,'BN');
INSERT INTO rdap.country_code VALUES (100,'BG');
INSERT INTO rdap.country_code VALUES (854,'BF');
INSERT INTO rdap.country_code VALUES (108,'BI');
INSERT INTO rdap.country_code VALUES (116,'KH');
INSERT INTO rdap.country_code VALUES (120,'CM');
INSERT INTO rdap.country_code VALUES (124,'CA');
INSERT INTO rdap.country_code VALUES (132,'CV');
INSERT INTO rdap.country_code VALUES (136,'KY');
INSERT INTO rdap.country_code VALUES (140,'CF');
INSERT INTO rdap.country_code VALUES (148,'TD');
INSERT INTO rdap.country_code VALUES (152,'CL');
INSERT INTO rdap.country_code VALUES (156,'CN');
INSERT INTO rdap.country_code VALUES (344,'HK');
INSERT INTO rdap.country_code VALUES (446,'MO');
INSERT INTO rdap.country_code VALUES (162,'CX');
INSERT INTO rdap.country_code VALUES (166,'CC');
INSERT INTO rdap.country_code VALUES (170,'CO');
INSERT INTO rdap.country_code VALUES (174,'KM');
INSERT INTO rdap.country_code VALUES (178,'CG');
INSERT INTO rdap.country_code VALUES (180,'CD');
INSERT INTO rdap.country_code VALUES (184,'CK');
INSERT INTO rdap.country_code VALUES (188,'CR');
INSERT INTO rdap.country_code VALUES (384,'CI');
INSERT INTO rdap.country_code VALUES (191,'HR');
INSERT INTO rdap.country_code VALUES (192,'CU');
INSERT INTO rdap.country_code VALUES (196,'CY');
INSERT INTO rdap.country_code VALUES (203,'CZ');
INSERT INTO rdap.country_code VALUES (208,'DK');
INSERT INTO rdap.country_code VALUES (262,'DJ');
INSERT INTO rdap.country_code VALUES (212,'DM');
INSERT INTO rdap.country_code VALUES (214,'DO');
INSERT INTO rdap.country_code VALUES (218,'EC');
INSERT INTO rdap.country_code VALUES (818,'EG');
INSERT INTO rdap.country_code VALUES (222,'SV');
INSERT INTO rdap.country_code VALUES (226,'GQ');
INSERT INTO rdap.country_code VALUES (232,'ER');
INSERT INTO rdap.country_code VALUES (233,'EE');
INSERT INTO rdap.country_code VALUES (231,'ET');
INSERT INTO rdap.country_code VALUES (238,'FK');
INSERT INTO rdap.country_code VALUES (234,'FO');
INSERT INTO rdap.country_code VALUES (242,'FJ');
INSERT INTO rdap.country_code VALUES (246,'FI');
INSERT INTO rdap.country_code VALUES (250,'FR');
INSERT INTO rdap.country_code VALUES (254,'GF');
INSERT INTO rdap.country_code VALUES (258,'PF');
INSERT INTO rdap.country_code VALUES (260,'TF');
INSERT INTO rdap.country_code VALUES (266,'GA');
INSERT INTO rdap.country_code VALUES (270,'GM');
INSERT INTO rdap.country_code VALUES (268,'GE');
INSERT INTO rdap.country_code VALUES (276,'DE');
INSERT INTO rdap.country_code VALUES (288,'GH');
INSERT INTO rdap.country_code VALUES (292,'GI');
INSERT INTO rdap.country_code VALUES (300,'GR');
INSERT INTO rdap.country_code VALUES (304,'GL');
INSERT INTO rdap.country_code VALUES (308,'GD');
INSERT INTO rdap.country_code VALUES (312,'GP');
INSERT INTO rdap.country_code VALUES (316,'GU');
INSERT INTO rdap.country_code VALUES (320,'GT');
INSERT INTO rdap.country_code VALUES (831,'GG');
INSERT INTO rdap.country_code VALUES (324,'GN');
INSERT INTO rdap.country_code VALUES (624,'GW');
INSERT INTO rdap.country_code VALUES (328,'GY');
INSERT INTO rdap.country_code VALUES (332,'HT');
INSERT INTO rdap.country_code VALUES (334,'HM');
INSERT INTO rdap.country_code VALUES (336,'VA');
INSERT INTO rdap.country_code VALUES (340,'HN');
INSERT INTO rdap.country_code VALUES (348,'HU');
INSERT INTO rdap.country_code VALUES (352,'IS');
INSERT INTO rdap.country_code VALUES (356,'IN');
INSERT INTO rdap.country_code VALUES (360,'ID');
INSERT INTO rdap.country_code VALUES (364,'IR');
INSERT INTO rdap.country_code VALUES (368,'IQ');
INSERT INTO rdap.country_code VALUES (372,'IE');
INSERT INTO rdap.country_code VALUES (833,'IM');
INSERT INTO rdap.country_code VALUES (376,'IL');
INSERT INTO rdap.country_code VALUES (380,'IT');
INSERT INTO rdap.country_code VALUES (388,'JM');
INSERT INTO rdap.country_code VALUES (392,'JP');
INSERT INTO rdap.country_code VALUES (832,'JE');
INSERT INTO rdap.country_code VALUES (400,'JO');
INSERT INTO rdap.country_code VALUES (398,'KZ');
INSERT INTO rdap.country_code VALUES (404,'KE');
INSERT INTO rdap.country_code VALUES (296,'KI');
INSERT INTO rdap.country_code VALUES (408,'KP');
INSERT INTO rdap.country_code VALUES (410,'KR');
INSERT INTO rdap.country_code VALUES (414,'KW');
INSERT INTO rdap.country_code VALUES (417,'KG');
INSERT INTO rdap.country_code VALUES (418,'LA');
INSERT INTO rdap.country_code VALUES (428,'LV');
INSERT INTO rdap.country_code VALUES (422,'LB');
INSERT INTO rdap.country_code VALUES (426,'LS');
INSERT INTO rdap.country_code VALUES (430,'LR');
INSERT INTO rdap.country_code VALUES (434,'LY');
INSERT INTO rdap.country_code VALUES (438,'LI');
INSERT INTO rdap.country_code VALUES (440,'LT');
INSERT INTO rdap.country_code VALUES (442,'LU');
INSERT INTO rdap.country_code VALUES (807,'MK');
INSERT INTO rdap.country_code VALUES (450,'MG');
INSERT INTO rdap.country_code VALUES (454,'MW');
INSERT INTO rdap.country_code VALUES (458,'MY');
INSERT INTO rdap.country_code VALUES (462,'MV');
INSERT INTO rdap.country_code VALUES (466,'ML');
INSERT INTO rdap.country_code VALUES (470,'MT');
INSERT INTO rdap.country_code VALUES (584,'MH');
INSERT INTO rdap.country_code VALUES (474,'MQ');
INSERT INTO rdap.country_code VALUES (478,'MR');
INSERT INTO rdap.country_code VALUES (480,'MU');
INSERT INTO rdap.country_code VALUES (175,'YT');
INSERT INTO rdap.country_code VALUES (484,'MX');
INSERT INTO rdap.country_code VALUES (583,'FM');
INSERT INTO rdap.country_code VALUES (498,'MD');
INSERT INTO rdap.country_code VALUES (492,'MC');
INSERT INTO rdap.country_code VALUES (496,'MN');
INSERT INTO rdap.country_code VALUES (499,'ME');
INSERT INTO rdap.country_code VALUES (500,'MS');
INSERT INTO rdap.country_code VALUES (504,'MA');
INSERT INTO rdap.country_code VALUES (508,'MZ');
INSERT INTO rdap.country_code VALUES (104,'MM');
INSERT INTO rdap.country_code VALUES (516,'NA');
INSERT INTO rdap.country_code VALUES (520,'NR');
INSERT INTO rdap.country_code VALUES (524,'NP');
INSERT INTO rdap.country_code VALUES (528,'NL');
INSERT INTO rdap.country_code VALUES (530,'AN');
INSERT INTO rdap.country_code VALUES (540,'NC');
INSERT INTO rdap.country_code VALUES (554,'NZ');
INSERT INTO rdap.country_code VALUES (558,'NI');
INSERT INTO rdap.country_code VALUES (562,'NE');
INSERT INTO rdap.country_code VALUES (566,'NG');
INSERT INTO rdap.country_code VALUES (570,'NU');
INSERT INTO rdap.country_code VALUES (574,'NF');
INSERT INTO rdap.country_code VALUES (580,'MP');
INSERT INTO rdap.country_code VALUES (578,'NO');
INSERT INTO rdap.country_code VALUES (512,'OM');
INSERT INTO rdap.country_code VALUES (586,'PK');
INSERT INTO rdap.country_code VALUES (585,'PW');
INSERT INTO rdap.country_code VALUES (275,'PS');
INSERT INTO rdap.country_code VALUES (591,'PA');
INSERT INTO rdap.country_code VALUES (598,'PG');
INSERT INTO rdap.country_code VALUES (600,'PY');
INSERT INTO rdap.country_code VALUES (604,'PE');
INSERT INTO rdap.country_code VALUES (608,'PH');
INSERT INTO rdap.country_code VALUES (612,'PN');
INSERT INTO rdap.country_code VALUES (616,'PL');
INSERT INTO rdap.country_code VALUES (620,'PT');
INSERT INTO rdap.country_code VALUES (630,'PR');
INSERT INTO rdap.country_code VALUES (634,'QA');
INSERT INTO rdap.country_code VALUES (638,'RE');
INSERT INTO rdap.country_code VALUES (642,'RO');
INSERT INTO rdap.country_code VALUES (643,'RU');
INSERT INTO rdap.country_code VALUES (646,'RW');
INSERT INTO rdap.country_code VALUES (652,'BL');
INSERT INTO rdap.country_code VALUES (654,'SH');
INSERT INTO rdap.country_code VALUES (659,'KN');
INSERT INTO rdap.country_code VALUES (662,'LC');
INSERT INTO rdap.country_code VALUES (663,'MF');
INSERT INTO rdap.country_code VALUES (666,'PM');
INSERT INTO rdap.country_code VALUES (670,'VC');
INSERT INTO rdap.country_code VALUES (882,'WS');
INSERT INTO rdap.country_code VALUES (674,'SM');
INSERT INTO rdap.country_code VALUES (678,'ST');
INSERT INTO rdap.country_code VALUES (682,'SA');
INSERT INTO rdap.country_code VALUES (686,'SN');
INSERT INTO rdap.country_code VALUES (688,'RS');
INSERT INTO rdap.country_code VALUES (690,'SC');
INSERT INTO rdap.country_code VALUES (694,'SL');
INSERT INTO rdap.country_code VALUES (702,'SG');
INSERT INTO rdap.country_code VALUES (703,'SK');
INSERT INTO rdap.country_code VALUES (705,'SI');
INSERT INTO rdap.country_code VALUES (90,'SB');
INSERT INTO rdap.country_code VALUES (706,'SO');
INSERT INTO rdap.country_code VALUES (710,'ZA');
INSERT INTO rdap.country_code VALUES (239,'GS');
INSERT INTO rdap.country_code VALUES (728,'SS');
INSERT INTO rdap.country_code VALUES (724,'ES');
INSERT INTO rdap.country_code VALUES (144,'LK');
INSERT INTO rdap.country_code VALUES (736,'SD');
INSERT INTO rdap.country_code VALUES (740,'SR');
INSERT INTO rdap.country_code VALUES (744,'SJ');
INSERT INTO rdap.country_code VALUES (748,'SZ');
INSERT INTO rdap.country_code VALUES (752,'SE');
INSERT INTO rdap.country_code VALUES (756,'CH');
INSERT INTO rdap.country_code VALUES (760,'SY');
INSERT INTO rdap.country_code VALUES (158,'TW');
INSERT INTO rdap.country_code VALUES (762,'TJ');
INSERT INTO rdap.country_code VALUES (834,'TZ');
INSERT INTO rdap.country_code VALUES (764,'TH');
INSERT INTO rdap.country_code VALUES (626,'TL');
INSERT INTO rdap.country_code VALUES (768,'TG');
INSERT INTO rdap.country_code VALUES (772,'TK');
INSERT INTO rdap.country_code VALUES (776,'TO');
INSERT INTO rdap.country_code VALUES (780,'TT');
INSERT INTO rdap.country_code VALUES (788,'TN');
INSERT INTO rdap.country_code VALUES (792,'TR');
INSERT INTO rdap.country_code VALUES (795,'TM');
INSERT INTO rdap.country_code VALUES (796,'TC');
INSERT INTO rdap.country_code VALUES (798,'TV');
INSERT INTO rdap.country_code VALUES (800,'UG');
INSERT INTO rdap.country_code VALUES (804,'UA');
INSERT INTO rdap.country_code VALUES (784,'AE');
INSERT INTO rdap.country_code VALUES (826,'GB');
INSERT INTO rdap.country_code VALUES (840,'US');
INSERT INTO rdap.country_code VALUES (581,'UM');
INSERT INTO rdap.country_code VALUES (858,'UY');
INSERT INTO rdap.country_code VALUES (860,'UZ');
INSERT INTO rdap.country_code VALUES (548,'VU');
INSERT INTO rdap.country_code VALUES (862,'VE');
INSERT INTO rdap.country_code VALUES (704,'VN');
INSERT INTO rdap.country_code VALUES (850,'VI');
INSERT INTO rdap.country_code VALUES (876,'WF');
INSERT INTO rdap.country_code VALUES (732,'EH');
INSERT INTO rdap.country_code VALUES (887,'YE');
INSERT INTO rdap.country_code VALUES (894,'ZM');
INSERT INTO rdap.country_code VALUES (716,'ZW');


INSERT INTO rdap.ip_version VALUES (4, 'v4');
INSERT INTO rdap.ip_version VALUES (6, 'v6');

INSERT INTO rdap.configuration VALUE ('schema', null, null, 'Current scheme used by the application.', '2017-01-27 12:00:00', null);

commit;